[package]
name = "orders-benchmarking"
version = "2.1.0"
authors = ["agustinustheoo <agustinustheoo@gmail.com>"]
edition = '2021'
description = ''
homepage = ''
license = 'Unlicense'

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

# alias "parity-scale-code" to "codec"
[dependencies.codec]
default-features = false
features = ['derive']
package = 'parity-scale-codec'
version = '2.0.0'

[dependencies]
hex-literal = '0.3.3'
frame-support = { version = "4.0.0-dev", default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.18" }
frame-system = { version = "4.0.0-dev", default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.18" }
frame-benchmarking = { version = "4.0.0-dev", default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.18" }

pallet-balances = { version = "4.0.0-dev", default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.18" }

sp-std = { version = "4.0.0-dev", default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.18" }
sp-io = { version = "6.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.18" }
sp-core = { version = "6.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.18" }
sp-runtime = { version = "6.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.18" }

labs = { path = '../../labs', default-features = false }
services = { path = '../../services', default-features = false }
user-profile = { path = '../../user-profile', default-features = false }
orders = { path = '../../orders', default-features = false }
genetic-testing = { path = '../../genetic-testing', default-features = false }

traits-services = { path = '../../services/traits', default-features = false }
traits-user-profile = { path = '../../user-profile/traits', default-features = false }
traits-order = { path = '../../orders/traits', default-features = false }
traits-genetic-testing = { path = '../../genetic-testing/traits', default-features = false }

primitives-duration = { path = '../../../primitives/duration', default-features = false }
primitives-area-code = { path = '../../../primitives/area-code', default-features = false }
primitives-price-and-currency = { path = '../../../primitives/price-and-currency', default-features = false }

[dev-dependencies]
serde = { default-features = false, version = "1.0.130" }

[features]
default = ['std']
std = [
    'codec/std',

    'sp-io/std',
    'sp-core/std',
    'sp-runtime/std',

    'frame-benchmarking/std',
    'frame-support/std',
    'frame-system/std',

	'pallet-balances/std',

    'labs/std',
    'services/std',
    'user-profile/std',
    'orders/std',
    'genetic-testing/std',

    'primitives-duration/std',
    'primitives-area-code/std',
    'primitives-price-and-currency/std',

    'traits-services/std',
    'traits-user-profile/std',
    'traits-order/std',
    'traits-genetic-testing/std',
]
