[package]
name = "genetic-analysis-orders-benchmarking"
version = "2.1.0"
authors = ["agustinustheoo <agustinustheoo@gmail.com>"]
edition = '2021'
description = ''
homepage = ''
license = 'Unlicense'

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

# alias "parity-scale-code" to "codec"
[dependencies.codec]
default-features = false
features = ['derive']
package = 'parity-scale-codec'
version = '2.0.0'

[dependencies]
hex-literal = '0.3.3'
frame-support = { git = 'https://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.13', default-features = false }
frame-system = { git = 'https://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.13', default-features = false }
frame-benchmarking = { git = 'https://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.13', default-features = false }

pallet-timestamp = { git = 'https://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.13', default-features = false }
pallet-balances = { git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.13', default-features = false }

sp-std = { git = 'https://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.13', default-features = false }
sp-io = { git = 'https://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.13', default-features = false }
sp-core = { git = 'https://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.13', default-features = false }
sp-runtime = { git = 'https://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.13', default-features = false }

genetic-analysts = { path = '../../genetic-analysts', default-features = false }
genetic-analyst-services = { path = '../../genetic-analyst-services', default-features = false }
genetic-analyst-qualifications = { path = '../../genetic-analyst-qualifications', default-features = false }
genetic-analysis = { path = '../../genetic-analysis', default-features = false }
genetic-analysis-orders = { path = '../../genetic-analysis-orders', default-features = false }
genetic-data = { path = '../../genetic-data', default-features = false }
user-profile = { path = '../../user-profile', default-features = false }

primitives-duration = { path = '../../../primitives/duration', default-features = false }
primitives-tracking-id = { path = '../../../primitives/tracking-id', default-features = false }
primitives-price-and-currency = { path = '../../../primitives/price-and-currency', default-features = false }
primitives-availability-status = { path = '../../../primitives/availability-status', default-features = false }

traits-genetic-analyst-services = { path = '../../genetic-analyst-services/traits', default-features = false }
traits-genetic-analysis = { path = '../../genetic-analysis/traits', default-features = false }
traits-genetic-analysis-orders = { path = '../../genetic-analysis-orders/traits', default-features = false }
traits-genetic-data = { path = '../../genetic-data/traits', default-features = false }
traits-user-profile = { path = '../../user-profile/traits', default-features = false }

[dev-dependencies]
serde = { default-features = false, version = "1.0.130" }

[features]
default = ['std']
std = [
    'codec/std',

    'sp-io/std',
    'sp-core/std',
    'sp-runtime/std',

    'frame-benchmarking/std',
    'frame-support/std',
    'frame-system/std',

	'pallet-timestamp/std',
	'pallet-balances/std',

    'genetic-analysts/std',
    'genetic-analyst-services/std',
	'genetic-analyst-qualifications/std',
	'genetic-analysis/std',
	'genetic-analysis-orders/std',
	'genetic-data/std',
    'user-profile/std',

    'primitives-duration/std',
    'primitives-tracking-id/std',
    'primitives-price-and-currency/std',
    'primitives-availability-status/std',

    'traits-genetic-analyst-services/std',
    'traits-genetic-analysis/std',
    'traits-genetic-analysis-orders/std',
    'traits-genetic-data/std',
    'traits-user-profile/std',
]
