version: '3'

services:
  node:
    container_name: debio-node
    image: debionetwork/debio-node
    build:
      context: ../../
      dockerfile: .maintain/docker/Dockerfile
    volumes:
      - data:/data
    command: >
      --base-path /data
      --dev
      --alice
      --enable-offchain-indexing
      --rpc-cors all
      --rpc-methods unsafe
      --unsafe-rpc-external
      --unsafe-ws-external
      --prometheus-external
      --no-telemetry
    ports:
      - 30333:30333
      - 9933:9933
      - 9944:9944
      - 9615:9615
    networks:
      debio:
        ipv4_address: 172.26.1.1
        aliases:
          - debio-node

volumes:
  data:

networks:
  debio:
    external: true
