[package]
name = "escrow-controller"
version = "0.1.0"
authors = ["kevin <kevin.janada@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package.metadata.substrate]
categories = [
	"trait",
]

compatibility_version = "2.0.0"


[dependencies]
# Substrate packages
sp-std = { git = 'https://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.12', default-features = false }
frame-system = { git = 'https://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.12', default-features = false }


[features]
default = ['std']
std = [
  'sp-std/std',
  'frame-system/std',
]
