[package]
name = "primitives-tracking-id"
version = "2.1.0"
authors = ["Agustinus Theodorus <agustinustheoo@gmail.com>"]
edition = '2021'

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive", "max-encoded-len"] }
sp-std = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.30" }
scale-info = { version = "2.1.1", default-features = false, features = ["derive"] }
frame-support = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.30" }

[features]
default = ['std']
std = [
  'sp-std/std',
  'scale-info/std',
  'frame-support/std',
]

