[package]
name = 'rewards'
version = '0.1.0'
edition = '2018'
license = 'Unlicense'
authors = ['Debio Dev Team <https://github/debionetwork>']
description = 'rewards pallet'
homepage = 'https://debio.network'
repository = 'https://github.com/debionetwork/debio-node'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies.codec]
default-features = false
features = ['derive']
package = 'parity-scale-codec'
version = '2.0.0'

[dependencies]
serde = { default-features = false, version = "1.0.119", features = ["derive"] }
sp-std = { default-features = false, version = '3.0.0' }
frame-support = { default-features = false, version = '3.0.0' }
frame-system = { default-features = false, version = '3.0.0' }
user-profile = { default-features = false, path = '../user-profile', version = '0.1.0'}
genetic-testing = { default-features = false, path= '../genetic-testing', version = '0.1.0'}

[dev-dependencies]
sp-core = { default-features = false, version = '3.0.0' }
sp-runtime = { default-features = false, version = '3.0.0' }
sp-io = { default-features = false, version = '3.0.0' }


[features]
default = ['std']
std = [
    'serde/std',
	'codec/std',
	'sp-std/std',
    'sp-io/std',
	'frame-support/std',
	'frame-system/std',
	'user-profile/std',
]