[package]
name = 'labs'
version = '0.1.0'
repository = ''
edition = '2018'
authors = ['kevin <kevin.janada@gmail.com>']
description = ''
homepage = ''
license = 'Unlicense'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

# alias "parity-scale-code" to "codec"
[dependencies.codec]
default-features = false
features = ['derive']
package = 'parity-scale-codec'
version = '1.3.4'

[dependencies]
frame-support = { default-features = false, version = '2.0.1' }
frame-system = { default-features = false, version = '2.0.1' }
sp-core = { default-features = false, version = '2.0.1' }
services = { path = '../services', default-features = false }
service-owner = { path = '../../traits/service-owner', default-features = false }

[dev-dependencies]
sp-io = { default-features = false, version = '2.0.1' }
sp-runtime = { default-features = false, version = '2.0.1' }

[features]
default = ['std']
std = [
    'codec/std',
    'frame-support/std',
    'frame-system/std',
    'sp-core/std',
    'services/std',
    'service-owner/std',
]
