[package]
name = 'genetic-analysts-benchmarking'
version = "2.1.0"
repository = ''
edition = '2021'
authors = ['agustinustheoo <agustinustheoo@gmail.com>']
description = ''
homepage = ''
license = 'AGPL-3.0'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
scale-info = { version = "2.0.1", default-features = false, features = ["derive"] }
frame-support = { version = "4.0.0-dev", default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.18" }
frame-system = { version = "4.0.0-dev", default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.18" }
sp-std = { version = "4.0.0-dev", default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.18" }
sp-io = { version = "6.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.18" }
frame-benchmarking = { version = "4.0.0-dev", default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.18" }

primitives-stake-status = { path = '../../../primitives/stake-status', default-features = false }
primitives-verification-status = { path = '../../../primitives/verification-status', default-features = false }
primitives-availability-status = { path = '../../../primitives/availability-status', default-features = false }

traits-user-profile = { path = '../../user-profile/traits', default-features = false }
traits-genetic-analysts = { path = '../traits', default-features = false }
traits-genetic-analysis-orders = { path = '../../genetic-analysis-orders/traits', default-features = false }
traits-genetic-analyst-services = { path = '../../genetic-analyst-services/traits', default-features = false }
traits-genetic-analyst-qualifications = { path = '../../genetic-analyst-qualifications/traits', default-features = false }

## Substrate Pallet Dependencies
pallet-timestamp = { version = "4.0.0-dev", default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.18" }
pallet-balances = { version = "4.0.0-dev", default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.18" }
pallet-randomness-collective-flip = { version = "4.0.0-dev", default-features = false, git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.18" }

## Local Dependencies
genetic-analysts = { path = '../../genetic-analysts', default-features = false }
genetic-analyst-services = { path = '../../genetic-analyst-services', default-features = false }
genetic-analyst-qualifications = { path = '../../genetic-analyst-qualifications', default-features = false }
genetic-analysis = { path = '../../genetic-analysis', default-features = false }
genetic-analysis-orders = { path = '../../genetic-analysis-orders', default-features = false }
genetic-data = { path = '../../genetic-data', default-features = false }
user-profile = { path = '../../user-profile', default-features = false }

[dev-dependencies]
serde = { default-features = false, version = "1.0.136" }
sp-core = { version = "6.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.18" }
sp-runtime = { version = "6.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.18" }

[features]
default = ['std']
std = [
    'codec/std',
	'scale-info/std',
    'frame-support/std',
    'frame-system/std',
    'frame-benchmarking/std',
    'sp-std/std',
    'sp-io/std',

    'primitives-verification-status/std',
    'primitives-availability-status/std',

    'traits-user-profile/std',
    'traits-genetic-analysts/std',
    'traits-genetic-analysis-orders/std',
    'traits-genetic-analyst-services/std',
    'traits-genetic-analyst-qualifications/std',

	'pallet-balances/std',
    'pallet-timestamp/std',
	'pallet-randomness-collective-flip/std',

    'genetic-analysts/std',
    'genetic-analyst-services/std',
	'genetic-analyst-qualifications/std',
	'genetic-analysis/std',
	'genetic-analysis-orders/std',
	'genetic-data/std',
	'user-profile/std',
]
try-runtime = ['frame-support/try-runtime']
